d3 = undefined
dims = undefined
splash = undefined
$ = undefined
$ = require('jQuery')
d3 = require('d3')
dims =
  width: window.innerWidth
  height: window.innerHeight

splash = ->
  path = undefined
  polygon = undefined
  redraw = undefined
  svg = undefined
  vertices = undefined
  voronoi = undefined

  redraw = ->
    path = path.data(voronoi(vertices), polygon)
    path.exit().remove()
    path.enter().append('path').attr
      'class': (d, i) ->
        'q' + i % 3 + '-9'
      'd': polygon
    path.order()

  polygon = (d) ->
    'M' + d.join('L') + 'Z'

  vertices = d3.range(200).map((d) ->
    [
      Math.random() * dims.width
      Math.random() * dims.height
    ]
  )
  voronoi = d3.geom.voronoi().clipExtent([
    [
      0
      0
    ]
    [
      dims.width
      dims.height
    ]
  ])
  svg = d3.select('.cell-background').append('svg').attr(
    'width': dims.width
    'height': dims.height).on('mousemove', ->
    vertices[0] = d3.mouse(this)
    redraw()
  )
  path = svg.append('g').selectAll('path')
  $(window).resize redraw
  redraw()

module.exports = splash

# ---
# generated by js2coffee 2.2.0