// Generated by CoffeeScript 1.10.0
var TableComponent, format;

format = d3.format('.3s');

TableComponent = React.createClass({displayName: "TableComponent",
  render: function() {
    return React.createElement("table", {
      "className": "table table-condensed table-hover table-striped mb-oxygen"
    }, React.createElement("tbody", null, React.createElement("tr", null, React.createElement("td", null, (this.props.activeBarsCategory === 'default' ? 'Geography:' : this.props.activeBarsCategory + ':')), React.createElement("td", null, React.createElement("strong", null, (this.props.activeBarsValue === 'default' ? 'England \& Wales' : this.props.activeBarsValue)))), React.createElement("tr", null, React.createElement("td", null, "Total population:"), React.createElement("td", null, React.createElement("strong", null, (this.props.data.bars.sum != null ? format(this.props.data.bars.sum) : '')))), React.createElement("tr", null, React.createElement("td", null, "Total male:"), React.createElement("td", null, React.createElement("strong", null, (this.props.data.bars.malesSum != null ? format(this.props.data.bars.malesSum) : '')))), React.createElement("tr", null, React.createElement("td", null, "Total female:"), React.createElement("td", null, React.createElement("strong", null, (this.props.data.bars.femalesSum != null ? format(this.props.data.bars.femalesSum) : ''))))));
  }
});

module.exports = TableComponent;
