// Generated by CoffeeScript 1.10.0
var React, TableComponent;

React = require('react');

TableComponent = React.createClass({displayName: "TableComponent",
  newOptions: {
    category: 'table click category',
    value: 'table click value'
  },
  render: function() {
    return React.createElement("table", {
      "className": "table table-condensed table-hover table-striped",
      "onClick": ((function(_this) {
        return function() {
          return _this.props.onTableClick(_this.newOptions);
        };
      })(this))
    }, React.createElement("tbody", null, React.createElement("tr", null, React.createElement("th", null, React.createElement("strong", null, "Category")), React.createElement("th", null, React.createElement("strong", null, "Value"))), React.createElement("tr", null, React.createElement("td", null, "Category"), React.createElement("td", null, this.props.category)), React.createElement("tr", null, React.createElement("td", null, "Value"), React.createElement("td", null, this.props.value))));
  }
});

module.exports = TableComponent;

//# sourceMappingURL=pyramid-table.map
