// Generated by CoffeeScript 1.10.0
var Jumbotron;

Jumbotron = function() {
  return React.createElement("div", {
    "className": "jumbotron"
  }, React.createElement("div", {
    "className": "container"
  }, React.createElement("h1", null, "Hello, world!"), React.createElement("p", null, "This is a template for a simple marketing or informational website. It includes a large callout called a jumbotron and three supporting pieces of content. Use it as a starting point to create something more unique."), React.createElement("p", null, React.createElement("a", {
    "className": "btn btn-primary btn-lg",
    "href": "#",
    "role": "button"
  }, "Learn more »"))));
};

module.exports = Jumbotron;

//# sourceMappingURL=jumbotron.map
