// Generated by CoffeeScript 1.10.0
var Jumbotron;

Jumbotron = function() {
  return React.createElement("div", {
    "className": "jumbotron mb-white-text text-center mb-roboto col-sm-8 col-sm-offset-2 mb-zero mb-no-pointer-events"
  }, React.createElement("div", {
    "className": "container"
  }, React.createElement("h1", {
    "className": "mb-bold"
  }, "MB App"), React.createElement("p", null, "A series of interactive data visualizations showcasing British population statistics."), React.createElement("p", null, React.createElement("a", {
    "className": "btn btn-default mb-btn-primary btn-lg mb-all-pointer-events",
    "href": "/census",
    "role": "button"
  }, "View all »"))));
};

module.exports = Jumbotron;

//# sourceMappingURL=jumbotron.map
