// Generated by CoffeeScript 1.10.0
var Row, ThumbnailsRowComponent, thumbnailsData;

ThumbnailsRowComponent = require('../partials/thumbnails-row.js');

thumbnailsData = require('../page-data/index/featured-thumbnails.js');

Row = function() {
  return React.createElement("div", {
    "className": "container mb-white-text mb-roboto mb-no-pointer-events"
  }, React.createElement(ThumbnailsRowComponent, {
    "data": thumbnailsData
  }));
};

module.exports = Row;
