// Generated by CoffeeScript 1.10.0
var Row;

Row = function() {
  return React.createElement("div", {
    "className": "container"
  }, React.createElement("div", {
    "className": "row"
  }, React.createElement("div", {
    "className": "col-md-4"
  }, React.createElement("h2", null, "Heading"), React.createElement("p", null, "Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. "), React.createElement("p", null, React.createElement("a", {
    "className": "btn btn-default",
    "href": "#",
    "role": "button"
  }, "View details »"))), React.createElement("div", {
    "className": "col-md-4"
  }, React.createElement("h2", null, "Heading"), React.createElement("p", null, "Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. "), React.createElement("p", null, React.createElement("a", {
    "className": "btn btn-default",
    "href": "#",
    "role": "button"
  }, "View details »"))), React.createElement("div", {
    "className": "col-md-4"
  }, React.createElement("h2", null, "Heading"), React.createElement("p", null, "Donec sed odio dui. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Vestibulum id ligula porta felis euismod semper. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus."), React.createElement("p", null, React.createElement("a", {
    "className": "btn btn-default",
    "href": "#",
    "role": "button"
  }, "View details »")))), React.createElement("hr", null), React.createElement("footer", null, React.createElement("p", null, "© 2016 MB")));
};

module.exports = Row;

//# sourceMappingURL=row.map
