// Generated by CoffeeScript 1.10.0
var d3, drawBarChart;

d3 = require('d3');

drawBarChart = function(options) {
  var activeCategory, activeValue, container, data, isDefault, onInitDone, onMouseOver;
  container = options.container, data = options.data, isDefault = options.isDefault, onMouseOver = options.onMouseOver, activeCategory = options.activeCategory, activeValue = options.activeValue, onInitDone = options.onInitDone;
  my.init = function() {};
  my.update = function() {};
  my.width = function(value) {
    var width;
    if (!arguments.length) {
      return width;
    }
    width = value;
    return my;
  };
  my.height = function(value) {
    var height;
    if (!arguments.length) {
      return height;
    }
    height = value;
    return my;
  };
  return my;
};

module.exports = drawBarChart;

//# sourceMappingURL=bar-chart.map
