// Generated by CoffeeScript 1.10.0
var React, pyBarsComponent;

React = require('react');

pyBarsComponent = React.createClass({displayName: "pyBarsComponent",
  render: function() {
    return React.createElement("div", null, React.createElement("svg", {
      "className": "pyramid-bars-svg",
      "style": {
        width: '100%',
        height: '250px'
      },
      "ref": "pyramidBarsSvg"
    }));
  }
});

module.exports = pyBarsComponent;

//# sourceMappingURL=pyramid-bars.map
