// Generated by CoffeeScript 1.10.0
var Pyramid, PyramidComponent, Table, TableComponent, connect, mapDispatchToProps, mapStateToProps, toggleFilter;

connect = require('react-redux').connect;

toggleFilter = require('../actions/actions.js').toggleFilter;

PyramidComponent = require('../../ui/demographics/pyramid-component.js');

TableComponent = require('../../ui/demographics/pyramid-table.js');

mapStateToProps = function(state) {
  return {
    category: state.filterOptions.options.category,
    value: state.filterOptions.options.value
  };
};

mapDispatchToProps = function(dispatch) {
  return {
    onTableClick: function(options) {
      return dispatch(toggleFilter(options));
    }
  };
};

Pyramid = connect(mapStateToProps, mapDispatchToProps)(PyramidComponent);

Table = connect(mapStateToProps, mapDispatchToProps)(TableComponent);

module.exports = {
  Pyramid: Pyramid,
  Table: Table
};

//# sourceMappingURL=containers.map
