// Generated by CoffeeScript 1.10.0
var Pyramid, PyramidComponent, Table, TableComponent, connect, mapDispatchToProps, mapStateToProps, toggleCategory;

connect = require('react-redux').connect;

toggleCategory = require('../actions/actions.js').toggleCategory;

PyramidComponent = require('../../ui/demographics/pyramid-component.js');

TableComponent = require('../../ui/demographics/pyramid-table.js');

mapStateToProps = function(state) {
  return {
    category: state.pyramidChart.category,
    value: state.pyramidChart.value,
    data: state.pyramidChart.data,
    showSpinner: state.pyramidChart.isFetching
  };
};

mapDispatchToProps = function(dispatch) {
  return {
    onCategoryChange: function(event) {
      return dispatch(toggleCategory(event.target.value));
    }
  };
};

Pyramid = connect(mapStateToProps, mapDispatchToProps)(PyramidComponent);

Table = connect(mapStateToProps, mapDispatchToProps)(TableComponent);

module.exports = {
  Pyramid: Pyramid,
  Table: Table
};
