// Generated by CoffeeScript 1.10.0
var Pyramid, PyramidComponent, Table, TableComponent, addFilter, connect, mapDispatchToProps, mapStateToProps, ref, removeFilter, toggleCategory, toggleOutlineCategory, toggleValue;

connect = require('react-redux').connect;

ref = require('../actions/demographics-actions.js'), toggleCategory = ref.toggleCategory, addFilter = ref.addFilter, toggleOutlineCategory = ref.toggleOutlineCategory, toggleValue = ref.toggleValue, removeFilter = ref.removeFilter;

PyramidComponent = require('../../ui/demographics/pyramid-component.js');

TableComponent = require('../../ui/demographics/pyramid-table.js');

mapStateToProps = function(state) {
  return {
    chartName: state.pyramidChart.chartName,
    category: state.pyramidChart.category,
    value: state.pyramidChart.value,
    data: state.pyramidChart.data,
    showSpinner: state.pyramidChart.isFetching,
    outlineFilter: state.pyramidChart.outlineFilter,
    outlineCategory: state.pyramidChart.outlineCategory
  };
};

mapDispatchToProps = function(dispatch) {
  return {
    onCategoryChange: function(category) {
      return dispatch(toggleCategory(category));
    },
    onValueChange: function(value) {
      return dispatch(toggleValue(value));
    },
    onAddOutline: function() {
      return dispatch(addFilter());
    },
    onRemoveFilter: function() {
      return dispatch(removeFilter());
    },
    onOutlineCategoryChange: function(value) {
      return dispatch(toggleOutlineCategory(value));
    }
  };
};

Pyramid = connect(mapStateToProps, mapDispatchToProps)(PyramidComponent);

Table = connect(mapStateToProps, mapDispatchToProps)(TableComponent);

module.exports = {
  Pyramid: Pyramid,
  Table: Table
};
