// Generated by CoffeeScript 1.10.0
var MOUSE_OVER, TOGGLE_CATEGORY, TOGGLE_FILTER, mouseOver, toggleCategory, toggleFilter;

TOGGLE_FILTER = "TOGGLE_FILTER";

TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

MOUSE_OVER = "MOUSE_OVER";

toggleFilter = function(filterOptions) {
  return {
    type: TOGGLE_FILTER,
    filterOptions: filterOptions
  };
};

toggleCategory = function(category) {
  return {
    type: TOGGLE_CATEGORY,
    category: category
  };
};

mouseOver = function(mouseOverOptions) {
  return {
    type: MOUSE_OVER,
    mouseOverOptions: mouseOverOptions
  };
};

module.exports = {
  TOGGLE_FILTER: TOGGLE_FILTER,
  TOGGLE_CATEGORY: TOGGLE_CATEGORY,
  MOUSE_OVER: MOUSE_OVER,
  toggleFilter: toggleFilter,
  toggleCategory: toggleCategory,
  mouseOver: mouseOver
};

//# sourceMappingURL=actions.map
