// Generated by CoffeeScript 1.10.0
var MOUSE_OVER, TOGGLE_CATEGORY, mouseOver, toggleCategory;

TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

MOUSE_OVER = "MOUSE_OVER";

toggleCategory = function(category) {
  return {
    type: TOGGLE_CATEGORY,
    category: category
  };
};

mouseOver = function(mouseOverOptions) {
  return {
    type: MOUSE_OVER,
    mouseOverOptions: mouseOverOptions
  };
};

module.exports = {
  TOGGLE_CATEGORY: TOGGLE_CATEGORY,
  MOUSE_OVER: MOUSE_OVER,
  toggleCategory: toggleCategory,
  mouseOver: mouseOver
};

//# sourceMappingURL=actions.map
