// Generated by CoffeeScript 1.10.0
var RECEIVE_PYRAMID_DATA, REQUEST_PYRAMID_DATA, fetchPyramidData, pyramidService, receivePyramidData, requestPyramidData;

pyramidService = require('../../services/nomis/pyramid-service.js');

REQUEST_PYRAMID_DATA = "REQUEST_PYRAMID_DATA";

RECEIVE_PYRAMID_DATA = "RECEIVE_PYRAMID_DATA";

requestPyramidData = function(filterOptions) {
  return {
    type: REQUEST_PYRAMID_DATA,
    filterOptions: filterOptions
  };
};

receivePyramidData = function(data) {
  return {
    type: RECEIVE_PYRAMID_DATA,
    data: data,
    receivedAt: Date.now()
  };
};

fetchPyramidData = function(filterOptions) {
  return function(dispatch) {
    dispatch(requestPyramidData(filterOptions));
    return pyramidService(filterOptions).done(function(response) {
      dispatch(receivePyramidData(response.obs));
    }).fail(function(jqxhr, textStatus, error) {
      console.log(textStatus + " - " + error);
    });
  };
};

module.exports = {
  RECEIVE_PYRAMID_DATA: RECEIVE_PYRAMID_DATA,
  REQUEST_PYRAMID_DATA: REQUEST_PYRAMID_DATA,
  receivePyramidData: receivePyramidData,
  requestPyramidData: requestPyramidData,
  fetchPyramidData: fetchPyramidData
};

//# sourceMappingURL=demographics-actions.map
