// Generated by CoffeeScript 1.10.0
var ADD_FILTER, MOUSE_OVER, RECEIVE_PYRAMID_DATA, REMOVE_FILTER, REQUEST_PYRAMID_DATA, TOGGLE_CATEGORY, TOGGLE_OUTLINE_CATEGORY, TOGGLE_OUTLINE_VALUE, TOGGLE_VALUE, addFilter, fetchPyramidData, mouseOver, pyramidService, receivePyramidData, removeFilter, requestPyramidData, toggleCategory, toggleOutlineCategory, toggleOutlineValue, toggleValue;

pyramidService = require('../../services/nomis/pyramid-service.js');

REQUEST_PYRAMID_DATA = "REQUEST_PYRAMID_DATA";

RECEIVE_PYRAMID_DATA = "RECEIVE_PYRAMID_DATA";

TOGGLE_CATEGORY = "TOGGLE_CATEGORY";

MOUSE_OVER = "MOUSE_OVER";

ADD_FILTER = "ADD_FILTER";

REMOVE_FILTER = "REMOVE_FILTER";

TOGGLE_OUTLINE_CATEGORY = "TOGGLE_OUTLINE_CATEGORY";

TOGGLE_OUTLINE_VALUE = "TOGGLE_OUTLINE_VALUE";

TOGGLE_VALUE = "TOGGLE_VALUE";

toggleValue = function(value, selectionOption) {
  return {
    type: TOGGLE_VALUE,
    value: value,
    selectionOption: selectionOption
  };
};

toggleOutlineCategory = function(category, selectionOption) {
  return {
    type: TOGGLE_OUTLINE_CATEGORY,
    category: category,
    selectionOption: selectionOption
  };
};

toggleOutlineValue = function(value, selectionOption) {
  return {
    type: TOGGLE_OUTLINE_VALUE,
    value: value,
    selectionOption: selectionOption
  };
};

addFilter = function() {
  return {
    type: ADD_FILTER
  };
};

removeFilter = function() {
  return {
    type: REMOVE_FILTER
  };
};

toggleCategory = function(category, selectionOption) {
  console.log('toggleCategory selectionOption');
  console.log(selectionOption);
  return {
    type: TOGGLE_CATEGORY,
    category: category,
    selectionOption: selectionOption
  };
};

mouseOver = function(mouseOverOptions) {
  return {
    type: MOUSE_OVER,
    mouseOverOptions: mouseOverOptions
  };
};

requestPyramidData = function(filterOptions) {
  return {
    type: REQUEST_PYRAMID_DATA,
    filterOptions: filterOptions
  };
};

receivePyramidData = function(data) {
  return {
    type: RECEIVE_PYRAMID_DATA,
    data: data,
    receivedAt: Date.now()
  };
};

fetchPyramidData = function(filterOptions) {
  return function(dispatch) {
    dispatch(requestPyramidData(filterOptions));
    return pyramidService(filterOptions).done(function(response) {
      dispatch(receivePyramidData(response.obs));
    }).fail(function(jqxhr, textStatus, error) {
      console.log(textStatus + " - " + error);
    });
  };
};

module.exports = {
  RECEIVE_PYRAMID_DATA: RECEIVE_PYRAMID_DATA,
  REQUEST_PYRAMID_DATA: REQUEST_PYRAMID_DATA,
  TOGGLE_CATEGORY: TOGGLE_CATEGORY,
  MOUSE_OVER: MOUSE_OVER,
  ADD_FILTER: ADD_FILTER,
  REMOVE_FILTER: REMOVE_FILTER,
  TOGGLE_OUTLINE_CATEGORY: TOGGLE_OUTLINE_CATEGORY,
  TOGGLE_OUTLINE_VALUE: TOGGLE_OUTLINE_VALUE,
  TOGGLE_VALUE: TOGGLE_VALUE,
  receivePyramidData: receivePyramidData,
  requestPyramidData: requestPyramidData,
  fetchPyramidData: fetchPyramidData,
  toggleCategory: toggleCategory,
  mouseOver: mouseOver,
  addFilter: addFilter,
  removeFilter: removeFilter,
  toggleOutlineCategory: toggleOutlineCategory,
  toggleValue: toggleValue,
  toggleOutlineValue: toggleOutlineValue
};
