// Generated by CoffeeScript 1.10.0
var combineReducers, mbReducer, objectAssign, pyramidChart;

combineReducers = require('redux').combineReducers;

objectAssign = require('object-assign');

pyramidChart = require('./demographics/pyramid-reducers.js');

mbReducer = combineReducers({
  pyramidChart: pyramidChart
});

module.exports = mbReducer;

//# sourceMappingURL=reducers.map
