// Generated by CoffeeScript 1.10.0
var combineReducers, ethnicSunburst, mbReducer, objectAssign, pyramidChart;

combineReducers = require('redux').combineReducers;

objectAssign = require('object-assign');

pyramidChart = require('./demographics/pyramid-reducers.js');

ethnicSunburst = require('./demographics/ethnic-sunburst-reducers.js');

mbReducer = combineReducers({
  pyramidChart: pyramidChart,
  ethnicSunburst: ethnicSunburst
});

module.exports = mbReducer;
