// Generated by CoffeeScript 1.10.0
var $, dataSet, defaultOptions, makePyramidRequest, nomisEndPoint;

$ = require('jQuery');

nomisEndPoint = "https://www.nomisweb.co.uk/api/v01/dataset/";

dataSet = "NM_657_1.data.json";

defaultOptions = {
  date: "date=latest",
  geography: "geography=K04000001",
  age: "c_age=1...21",
  sex: "c_sex=1,2",
  religion: "c_relpuk11=0"
};

makePyramidRequest = function(options) {
  var queryString, queryStringArr;
  if (options == null) {
    options = defaultOptions;
  }
  queryStringArr = [];
  queryString = (function() {
    var key, value;
    for (key in options) {
      value = options[key];
      queryStringArr.push(value);
    }
    return '?' + queryStringArr.join('&');
  })();
  return $.getJSON(nomisEndPoint + dataSet + queryString);
};

module.exports = makePyramidRequest;
