// Generated by CoffeeScript 1.10.0
var $, defaultOptions, ethDataSet, makePyramidRequest, nomisEndPoint, relDataSet,
  hasProp = {}.hasOwnProperty;

$ = require('jQuery');

nomisEndPoint = "https://www.nomisweb.co.uk/api/v01/dataset/";

relDataSet = "NM_657_1.data.json";

ethDataSet = "NM_651_1.data.json";

defaultOptions = {
  outlineRequested: false,
  bars: {
    isDefault: true,
    category: {
      label: 'default',
      value: 'default'
    },
    value: {
      label: 'default',
      value: 'default'
    }
  },
  outline: {
    isDefault: true,
    category: {
      label: 'default',
      value: 'default'
    },
    value: {
      label: 'default',
      value: 'default'
    }
  }
};

makePyramidRequest = function(options) {
  var defaultNomisOptions, generateDataObject, generateQueryString, getOptions, queryStringArr;
  defaultNomisOptions = {
    dataSet: relDataSet,
    queryStringOps: {
      date: "date=latest",
      geography: "geography=K04000001",
      age: "c_age=1...21",
      sex: "c_sex=1,2",
      religion: "c_relpuk11=0"
    }
  };
  queryStringArr = [];
  generateDataObject = function(o) {
    var catCode, catLabel, valCode, valLabel;
    catCode = o.category.value;
    catLabel = o.category.label;
    valLabel = o.value.label;
    valCode = o.value.value;
    return {
      dataSet: (function() {
        if (catCode === 'ethnicities') {
          return ethDataSet;
        } else {
          return relDataSet;
        }
      })(),
      queryStringOps: {
        date: "date=latest",
        age: "c_age=1...21",
        sex: "c_sex=1,2",
        geography: (function() {
          if (catLabel.indexOf('Geography') !== -1) {
            return "geography=" + valCode;
          } else {
            return "geography=K04000001";
          }
        })(),
        ethnicity: (function() {
          if (catCode === 'ethnicities') {
            return "c_ethpuk11=" + valCode;
          } else {
            return "";
          }
        })(),
        religion: (function() {
          if (catCode === 'religions') {
            return "c_relpuk11=" + valCode;
          } else if (catCode === 'ethnicities') {
            return "";
          } else {
            return "c_relpuk11=0";
          }
        })()
      }
    };
  };
  getOptions = function() {
    if (options != null) {
      return generateDataObject(options);
    } else {
      return defaultNomisOptions;
    }
  };
  generateQueryString = function(getOptions, queryStringArr) {
    var key, ref, value;
    ref = getOptions().queryStringOps;
    for (key in ref) {
      if (!hasProp.call(ref, key)) continue;
      value = ref[key];
      if (value !== "") {
        queryStringArr.push(value);
      }
    }
    return '?' + queryStringArr.join('&');
  };
  return $.getJSON(nomisEndPoint + getOptions().dataSet + generateQueryString(getOptions, queryStringArr));
};

module.exports = makePyramidRequest;
