// Generated by CoffeeScript 1.10.0
var GeneralHealthSection;

GeneralHealthSection = function() {
  return React.createElement("div", {
    "className": "row mb-quicksand"
  }, React.createElement("div", {
    "className": "hidden-xs col-sm-4"
  }, React.createElement("h3", {
    "className": "mb-section-header"
  }, "Ethnic Disparities in General Health ", React.createElement("button", {
    "className": "btn btn-info btn-xs",
    "type": "button",
    "data-toggle": "collapse",
    "data-target": "#ethnicCollapse",
    "aria-expanded": "false",
    "aria-controls": "ethnicCollapse"
  }, React.createElement("span", {
    "className": "glyphicon glyphicon-info-sign",
    "aria-hidden": "true"
  }), "\t\t\t\t\tinfo")), React.createElement("div", null, React.createElement("div", {
    "className": "collapse mb-quicksand",
    "id": "ethnicCollapse"
  }, React.createElement("div", {
    "className": "alert alert-block alert-info mb-section-text"
  }, React.createElement("button", {
    "type": "button",
    "className": "close",
    "data-toggle": "collapse",
    "data-target": "#ethnicCollapse",
    "aria-expanded": "false",
    "aria-controls": "ethnicCollapse"
  }, "×"), React.createElement("p", null, React.createElement("strong", null, "Overview")), React.createElement("p", null, "A question on self-assessed general health was included in the 2011 Census. The possible responses were \'Very good\', \'Good\', \'Fair\', \'Bad\' and \'Very bad\'."), React.createElement("p", null, "This chart combines the values for \'bad\' and \'very bad\' and plots these for 18 different ethnicities across six age groups."), React.createElement("p", null, React.createElement("strong", null, "Usage")), React.createElement("p", null, "Use the gender controls to re-plot the data for a specific gender. Highlight specific ethnicities by using the checkboxes, this will bring the selected ethnicity into focus along with revealing the % value with self-assessed bad\x2Fvery bad health for each age group.")))), React.createElement("div", {
    "className": "mb-oxygen mb-section-text"
  }, React.createElement("p", null, "The Ethnic Disparities in General Health chart shows the percentage of the population with self-assessed bad or very bad health broken down by age group and ethnicity.")), React.createElement("div", {
    "id": "general-health-details"
  })), React.createElement("div", {
    "className": "col-sm-8"
  }, React.createElement("div", {
    "id": "general-health-component"
  })));
};

module.exports = GeneralHealthSection;
