// Generated by CoffeeScript 1.10.0
var combineReducers, mbReducer, pyramidChart;

combineReducers = require('redux').combineReducers;

pyramidChart = require('../demographics/pyramid-reducers.js');

mbReducer = combineReducers({
  pyramidChart: pyramidChart
});

module.exports = mbReducer;
