// Generated by CoffeeScript 1.10.0
var Bars, Provider, Pyramid, React, ReactDOM, ReduxThunk, Table, applyMiddleware, compose, createStore, mbReducer, ref, ref1, render, store, unsubscribe;

ReactDOM = require('react-dom');

React = require('react');

ref = require('redux'), createStore = ref.createStore, applyMiddleware = ref.applyMiddleware, compose = ref.compose;

Provider = require('react-redux').Provider;

ReduxThunk = require('redux-thunk')["default"];

ref1 = require('../containers/demographics/pyramid-containers.js'), Pyramid = ref1.Pyramid, Table = ref1.Table, Bars = ref1.Bars;

mbReducer = require('../reducers/mb-reducers/population-pyramid.js');

store = createStore(mbReducer, compose(applyMiddleware(ReduxThunk)));

unsubscribe = store.subscribe(function() {});

render = function() {
  ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Pyramid, null)), document.getElementById('pyramid-container'));
  ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Table, null)), document.getElementById('pyramid-table'));
  return ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Bars, null)), document.getElementById('pyramid-bars'));
};

module.exports = render;
