// Generated by CoffeeScript 1.10.0
var Bars, Provider, Pyramid, ReduxThunk, Table, applyMiddleware, createStore, mbReducer, ref, ref1, render, store, unsubscribe;

ref = require('redux'), createStore = ref.createStore, applyMiddleware = ref.applyMiddleware;

Provider = require('react-redux').Provider;

ReduxThunk = require('redux-thunk')["default"];

ref1 = require('../containers/demographics/pyramid-containers.js'), Pyramid = ref1.Pyramid, Table = ref1.Table, Bars = ref1.Bars;

mbReducer = require('../reducers/mb-reducers/population-pyramid.js');

store = createStore(mbReducer, applyMiddleware(ReduxThunk));

console.log('getState 1');

console.log(store.getState());

unsubscribe = store.subscribe(function() {
  console.log('getState 2');
  return console.log(store.getState());
});

render = function() {
  ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Pyramid, null)), document.getElementById('pyramid-container'));
  ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Table, null)), document.getElementById('pyramid-table'));
  return ReactDOM.render(React.createElement(Provider, {
    "store": store
  }, React.createElement(Bars, null)), document.getElementById('pyramid-bars'));
};

module.exports = render;

//# sourceMappingURL=population-pyramid.map
