// Generated by CoffeeScript 1.10.0
var CensusIntro, Footer, Nav, PageHeader, ThumbnailsComponent, bootstrap, path;

window.React = require('react');

window.ReactDOM = require('react-dom');

window.d3 = require('d3');

window.$ = require('jquery');

bootstrap = require('../../bootstrap-sass/javascripts/bootstrap.min.js');

Nav = require('./partials/nav.js');

ThumbnailsComponent = require('./home/thumbnails-component.js');

CensusIntro = require('./home/census-intro.js');

PageHeader = require('./partials/page-header.js');

Footer = require('./partials/footer.js');

path = location.pathname.split('/')[1];

ReactDOM.render(React.createElement(PageHeader, {
  "page_header": path
}), document.getElementById('mb_page_header'));

ReactDOM.render(React.createElement(CensusIntro, null), document.getElementById('census_intro_row'));

ReactDOM.render(React.createElement(Nav, {
  "active": path,
  "border": "yes"
}), document.getElementById('react_nav_container'));

ReactDOM.render(React.createElement(ThumbnailsComponent, {
  "section": "Demographics"
}), document.getElementById('demographics_row'));

ReactDOM.render(React.createElement(ThumbnailsComponent, {
  "section": "Health"
}), document.getElementById('health_row'));

ReactDOM.render(React.createElement(ThumbnailsComponent, {
  "section": "Labour Market"
}), document.getElementById('labour_row'));

ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));

//# sourceMappingURL=home.map
