// Generated by CoffeeScript 1.10.0
var Jumbotron, Nav, NomisAttr, Row, bootstrap, path, voronoi;

window.React = require('react');

window.ReactDOM = require('react-dom');

window.d3 = require('d3');

window.$ = require('jquery');

voronoi = require('./voronoi.js');

bootstrap = require('../../bootstrap-sass/javascripts/bootstrap.min.js');

Nav = require('./partials/nav.js');

Jumbotron = require('./index/jumbotron.js');

Row = require('./index/row.js');

NomisAttr = require('./partials/nomis-attribution.js');

path = location.pathname.split('/')[1];

ReactDOM.render(React.createElement(Nav, {
  "active": 'home',
  "border": "yes"
}), document.getElementById('react_nav_container'));

ReactDOM.render(React.createElement(Jumbotron, null), document.getElementById('mb_hero'));

ReactDOM.render(React.createElement(Row, null), document.getElementById('mb_row'));

ReactDOM.render(React.createElement(NomisAttr, null), document.getElementById('mb_footer'));

voronoi();

//# sourceMappingURL=index.map
