// Generated by CoffeeScript 1.10.0
var Footer, MobilePortraitRotate, _path, bootstrap, bootstrap_tooltips, isMobilePortrait, path, raw_path, renderEmploymentStatusByCountry, renderEthnicDiversity, renderEthnicGenHealth, renderHealthDisability, renderPopulationPyramid, renderReligiousDiversity;

window.React = require('react');

window.ReactDOM = require('react-dom');

window.d3 = require('d3');

window.$ = require('jquery');

bootstrap = require('../../bootstrap-sass/javascripts/bootstrap.min.js');

bootstrap_tooltips = require('../../bootstrap-sass/javascripts/bootstrap/tooltip.js');

Footer = require('./partials/footer.js');

MobilePortraitRotate = require('./partials/mobile-portrait-rotate.js');

path = location.pathname.split('/')[1];

_path = path;

raw_path = location.pathname;

$("." + path).addClass('active');

isMobilePortrait = (function() {
  var window_width;
  window_width = $(window).width();
  if (window_width < 740) {
    return true;
  }
})();

renderPopulationPyramid = function() {
  var Nav, PageHeader, PopulationPyramid, render;
  render = require('./redux/renderers/population-pyramid.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  PopulationPyramid = require('./ui/demographics/static-components/population-pyramid.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": 'Population Pyramid - Census'
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(PopulationPyramid, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

renderEthnicDiversity = function() {
  var EthnicDiversity, Nav, PageHeader, render;
  render = require('./redux/renderers/ethnic-diversity.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  EthnicDiversity = require('./ui/demographics/static-components/ethnic-diversity.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": 'Ethnic Diversity - Census'
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(EthnicDiversity, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

renderReligiousDiversity = function() {
  var Nav, PageHeader, ReligiousDiversity, render;
  render = require('./redux/renderers/religious-diversity.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  ReligiousDiversity = require('./ui/demographics/static-components/religious-diversity.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": 'Religious Diversity - Census'
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(ReligiousDiversity, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

renderEthnicGenHealth = function() {
  var EthnicGenHealth, Nav, PageHeader, render;
  render = require('./redux/renderers/ethnic-general-health.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  EthnicGenHealth = require('./ui/health/static-components/general-health.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": "Ethnic Disparities in General Health - Census"
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(EthnicGenHealth, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

renderHealthDisability = function() {
  var HealthDisability, Nav, PageHeader, render;
  render = require('./redux/renderers/health-disability.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  HealthDisability = require('./ui/health/static-components/health-disability.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": "Long-term illness/disability by ethnicity - Census"
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(HealthDisability, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

renderEmploymentStatusByCountry = function() {
  var EconByCountry, Nav, PageHeader, render;
  render = require('./redux/renderers/econ-activity-country.js');
  PageHeader = require('./partials/page-header.js');
  Nav = require('./partials/nav.js');
  EconByCountry = require('./ui/labour/static-components/econ-activity-country.js');
  if (isMobilePortrait === true) {
    ReactDOM.render(React.createElement(MobilePortraitRotate, null), document.getElementById('mobile-portrait-container'));
  }
  ReactDOM.render(React.createElement(Nav, {
    "active": _path,
    "border": 'yes'
  }), document.getElementById('react_nav_container'));
  ReactDOM.render(React.createElement(PageHeader, {
    "page_header": "Employment status by country of birth - Census"
  }), document.getElementById('mb_page_header'));
  ReactDOM.render(React.createElement(EconByCountry, null), document.getElementById('react_container'));
  ReactDOM.render(React.createElement(Footer, null), document.getElementById('mb_footer'));
  return render();
};

switch (raw_path) {
  case '/demographics':
    renderDemographics();
    break;
  case '/health':
    renderHealth();
    break;
  case '/labour':
    renderLabour();
    break;
  case '/census/population-pyramid':
    renderPopulationPyramid();
    break;
  case '/census/ethnic-diversity':
    renderEthnicDiversity();
    break;
  case '/census/religious-diversity':
    renderReligiousDiversity();
    break;
  case '/census/ethnic-disparities-general-health':
    renderEthnicGenHealth();
    break;
  case '/census/longterm-illness-disability-by-ethnicity':
    renderHealthDisability();
    break;
  case '/census/employment-status-by-country-of-birth':
    renderEmploymentStatusByCountry();
}

$(function() {
  $('[data-toggle="tooltip"]').tooltip();
  return $('#mb_mc_signupform').css('visibility', 'visible');
});
