// Generated by CoffeeScript 1.10.0
var bootstrap, render;

bootstrap = require('../../bootstrap-sass/javascripts/bootstrap.js');

render = require('./redux/index.js');

render();

//# sourceMappingURL=ui.map
