// Generated by CoffeeScript 1.10.0
(function() {
  var $, bootstrap;

  bootstrap = require('../../bootstrap-sass/javascripts/bootstrap.js');

  $ = require('jQuery');

  module.exports = function() {
    $('#bs-example-navbar-collapse-1').on('show.bs.collapse', function() {
      console.log('add nav-stacked');
      return $('.nav-pills').addClass('nav-stacked');
    });
    return $('#bs-example-navbar-collapse-1').on('hide.bs.collapse', function() {
      console.log('remove nav-stacked');
      return $('.nav-pills').removeClass('nav-stacked');
    });
  };

}).call(this);
