// Generated by CoffeeScript 1.10.0
var d3;

d3 = require('d3');

module.exports = function(texts, width, x_margin) {
  if (x_margin == null) {
    x_margin = 0;
  }
  texts.each(function() {
    var dy, line, lineHeight, lineNumber, text, tspan, word, words, y;
    text = d3.select(this);
    words = text.text().split(/\s+/).reverse();
    word = void 0;
    line = [];
    lineNumber = 0;
    lineHeight = 1.1;
    y = text.attr('y');
    dy = parseFloat(text.attr('dy'));
    tspan = text.text(null).append('tspan').attr({
      x: x_margin,
      y: y,
      dy: dy + 'em'
    });

    /* jshint ignore:start */
    while (word = words.pop()) {
      line.push(word);
      tspan.text(line.join(' '));
      if (tspan.node().getComputedTextLength() > width) {
        line.pop();
        tspan.text(line.join(' '));
        line = [word];
        tspan = text.append('tspan').attr({
          x: x_margin,
          y: y
        }).attr('dy', ++lineNumber * lineHeight + dy + 'em').text(word);
      }
    }

    /* jshint ignore:end */
  });
};
