// Generated by CoffeeScript 1.10.0
(function() {
  var $;

  $ = require('jQuery');

  module.exports = (function() {
    var quoteIndex, quotes, showNextQuote;
    quotes = $(".mb-quotes");
    quoteIndex = -1;
    showNextQuote = function() {
      ++quoteIndex;
      return quotes.eq(quoteIndex % quotes.length).fadeIn(500).delay(500).fadeOut(500, showNextQuote);
    };
    return showNextQuote();
  })();

}).call(this);
