// Generated by CoffeeScript 1.10.0
var CensusIntro;

CensusIntro = function() {
  return React.createElement("div", {
    "className": "row col-sm-12"
  }, React.createElement("h2", {
    "className": "mb-oxygen"
  }, "Census Overview"), React.createElement("p", null, "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua."));
};

module.exports = CensusIntro;
