// Generated by CoffeeScript 1.10.0
var CensusIntro, React;

React = require('react');

CensusIntro = function() {
  return React.createElement("div", {
    "className": "row col-sm-12"
  }, React.createElement("h2", {
    "className": "mb-oxygen"
  }, "Census Overview"), React.createElement("p", null, "The census is a unique source of detailed socio-demographic statistics that underpins national policymaking with population estimates and projections to help allocate funding and plan investment and services. It is conducted every 10 years and is the richest source of social data we have. The following charts all use the 2011 Census for England \& Wales as their data source."));
};

module.exports = CensusIntro;
