// Generated by CoffeeScript 1.10.0
var DesktopNav;

DesktopNav = function() {
  return React.createElement("nav", {
    "className": "navbar navbar-default navbar-static-top hidden-xs"
  }, React.createElement("div", {
    "className": "container"
  }, React.createElement("div", {
    "className": "navbar-header"
  }, React.createElement("a", {
    "className": "navbar-brand mb-nav-brand-font",
    "href": "/"
  }, "MP App: node d3")), React.createElement("div", {
    "className": "container-fluid navbar-right"
  }, React.createElement("ul", {
    "className": "nav navbar-nav mb-oxygen mb-responsive-text-size"
  }, React.createElement("li", {
    "className": "demographics"
  }, React.createElement("a", {
    "href": "/demographics"
  }, "Demographics", React.createElement("span", {
    "className": "sr-only"
  }, "(current)"))), React.createElement("li", {
    "className": "health"
  }, React.createElement("a", {
    "href": "/health"
  }, "Health")), React.createElement("li", null, React.createElement("a", {
    "href": "labour"
  }, "Labour Market")), React.createElement("li", {
    "className": "about"
  }, React.createElement("a", {
    "href": "/about"
  }, "About"))))));
};

module.exports = DesktopNav;

//# sourceMappingURL=desktop-nav.map
