// Generated by CoffeeScript 1.10.0
var Footer;

Footer = function() {
  return React.createElement("div", {
    "className": "footer container mb-hidden-mp"
  }, React.createElement("hr", null), React.createElement("footer", null, React.createElement("p", null, "© 2016 Measuring Britain")));
};

module.exports = Footer;

//# sourceMappingURL=footer.map
