// Generated by CoffeeScript 1.10.0
var Footer;

Footer = function() {
  return React.createElement("div", {
    "className": "footer container"
  }, React.createElement("hr", null), React.createElement("footer", null, React.createElement("p", null, "© 2016 MB")));
};

module.exports = Footer;
