// Generated by CoffeeScript 1.10.0
var MobileNav;

MobileNav = function() {
  return React.createElement("nav", {
    "className": "navbar navbar-default navbar-static-top visible-xs"
  }, React.createElement("div", {
    "className": "container"
  }, React.createElement("div", {
    "className": "navbar-header"
  }, React.createElement("button", {
    "type": "button",
    "className": "navbar-toggle collapsed",
    "data-toggle": "collapse",
    "data-target": "#bs-example-navbar-collapse-1",
    "aria-expanded": "false"
  }, React.createElement("span", {
    "className": "sr-only"
  }, "Toggle navigation"), React.createElement("span", {
    "className": "icon-bar"
  }), React.createElement("span", {
    "className": "icon-bar"
  }), React.createElement("span", {
    "className": "icon-bar"
  })), React.createElement("a", {
    "className": "navbar-brand mb-nav-brand-font",
    "href": "/"
  }, "MP App: node d3")), React.createElement("div", {
    "className": "collapse navbar-collapse",
    "id": "bs-example-navbar-collapse-1"
  }, React.createElement("div", {
    "className": "container-fluid"
  }, React.createElement("ul", {
    "className": "nav navbar-nav"
  }, React.createElement("li", {
    "className": "demographics"
  }, React.createElement("a", {
    "href": "/demographics"
  }, "Demographics", React.createElement("span", {
    "className": "sr-only"
  }, "(current)"))), React.createElement("li", {
    "className": "health"
  }, React.createElement("a", {
    "href": "/health"
  }, "Health")), React.createElement("li", null, React.createElement("a", {
    "href": "labour"
  }, "Labour Market")), React.createElement("li", null, React.createElement("a", {
    "href": "about"
  }, "About")))))));
};

module.exports = MobileNav;

//# sourceMappingURL=mobile-nav.map
