// Generated by CoffeeScript 1.10.0
var NewsletterSignup;

NewsletterSignup = function() {
  return React.createElement("div", {
    "id": "mc_embed_signup",
    "className": "mb-hidden-mp"
  }, React.createElement("div", {
    "className": "container col-sm-6 col-sm-offset-3"
  }, React.createElement("form", {
    "action": "//measuringbritain.us13.list-manage.com/subscribe/post?u=a61fbfb347c2874094a4668e8&amp;id=782224cfee",
    "method": "post",
    "id": "mc-embedded-subscribe-form",
    "name": "mc-embedded-subscribe-form",
    "className": "validate",
    "target": "_blank",
    "noValidate": true
  }, React.createElement("div", {
    "id": "mc_embed_signup_scroll"
  }, React.createElement("label", {
    "htmlFor": "mce-EMAIL",
    "className": "mb-oxygen"
  }, "Get notified when new charts are added!"), React.createElement("input", {
    "type": "email",
    "value": "",
    "name": "EMAIL",
    "className": "email",
    "id": "mce-EMAIL",
    "placeholder": "Email address",
    "required": true
  }), React.createElement("div", {
    "style": {
      position: 'absolute',
      left: '-5000px'
    },
    "aria-hidden": "true"
  }, React.createElement("input", {
    "type": "text",
    "name": "b_a61fbfb347c2874094a4668e8_782224cfee",
    "tabIndex": "-1",
    "value": ""
  })), React.createElement("div", {
    "className": "clear"
  }, React.createElement("input", {
    "type": "submit",
    "value": "Subscribe",
    "name": "subscribe",
    "id": "mc-embedded-subscribe",
    "className": "button"
  }))))));
};

module.exports = NewsletterSignup;

//# sourceMappingURL=newsletter-signup.map
