// Generated by CoffeeScript 1.10.0
var ThumbnailsRowComponent;

ThumbnailsRowComponent = React.createClass({displayName: "ThumbnailsRowComponent",
  render: function() {
    return React.createElement("div", {
      "className": "row mb-oxygen"
    }, React.createElement("div", {
      "className": "col-sm-6 col-md-4"
    }, React.createElement("div", {
      "className": ""
    }, React.createElement("a", {
      "href": this.props.data[0].href,
      "className": "thumbnail mb-all-pointer-events"
    }, React.createElement("img", {
      "src": this.props.data[0].img,
      "alt": "..."
    })), React.createElement("div", {
      "className": "caption"
    }, React.createElement("h3", {
      "className": "mt-zero"
    }, this.props.data[0].chart_name), React.createElement("p", null, this.props.data[0].description), React.createElement("p", null, React.createElement("a", {
      "href": this.props.data[0].href,
      "className": "btn btn-default mb-btn-primary mb-all-pointer-events",
      "role": "button"
    }, "Explore"))))), React.createElement("div", {
      "className": "col-sm-6 col-md-4"
    }, React.createElement("div", {
      "className": ""
    }, React.createElement("a", {
      "href": this.props.data[1].href,
      "className": "thumbnail mb-all-pointer-events"
    }, React.createElement("img", {
      "src": this.props.data[1].img,
      "alt": "..."
    })), React.createElement("div", {
      "className": "caption"
    }, React.createElement("h3", {
      "className": "mt-zero"
    }, this.props.data[1].chart_name), React.createElement("p", null, this.props.data[1].description), React.createElement("p", null, React.createElement("a", {
      "href": this.props.data[1].href,
      "className": "btn btn-default mb-btn-primary mb-all-pointer-events",
      "role": "button"
    }, "Explore"))))), React.createElement("div", {
      "className": "col-sm-6 col-md-4"
    }, React.createElement("div", {
      "className": ""
    }, React.createElement("a", {
      "href": this.props.data[2].href,
      "className": "thumbnail mb-all-pointer-events"
    }, React.createElement("img", {
      "src": this.props.data[2].img,
      "alt": "..."
    })), React.createElement("div", {
      "className": "caption"
    }, React.createElement("h3", {
      "className": "mt-zero"
    }, this.props.data[2].chart_name), React.createElement("p", null, this.props.data[2].description, "."), React.createElement("p", null, React.createElement("a", {
      "href": this.props.data[2].href,
      "className": "btn btn-default mb-btn-primary mb-all-pointer-events",
      "role": "button"
    }, "Explore"))))));
  }
});

module.exports = ThumbnailsRowComponent;
