// Generated by CoffeeScript 1.10.0
var About;

About = function() {
  return React.createElement("div", null, React.createElement("div", {
    "className": "container col-md-6 col-md-offset-3"
  }, React.createElement("h1", {
    "className": "mb-white text-center mb-roboto-strong"
  }, "About Measuring Britain"), React.createElement("p", {
    "className": "mb-white"
  }, "Measuring Britain is a project aimed at making official statistics more accessible, interesting and fun through hand-crafted interactive charts and visualisations. We tackle three main areas of social life: Demographics, Health \& the Labour Market."), React.createElement("p", {
    "className": "mb-white"
  }, "The first phase of the project takes a fresh look at data from the 2011 census for England \& Wales. We\'ll be adding more visualisations regularly, focusing on more recent data. Sign up in order to be notified when new ones are added.")));
};

module.exports = About;
